package autosprogramgui;

import model.Auto;

public class AutoGui extends javax.swing.JFrame {

    private Auto a;

    public AutoGui() {
        initComponents();

        a = new Auto(true, false);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        allapotScrollPane = new javax.swing.JScrollPane();
        allapotTextArea = new javax.swing.JTextArea();
        cimLabel = new javax.swing.JLabel();
        funckiokPanel = new javax.swing.JPanel();
        tankolButton = new javax.swing.JButton();
        leallitasButton = new javax.swing.JButton();
        inditasButton = new javax.swing.JButton();
        defektCheckBox = new javax.swing.JCheckBox();
        potkerekTextField = new javax.swing.JTextField();
        potkerekLabel = new javax.swing.JLabel();
        kerekcsereButton = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        allapotTextArea.setColumns(20);
        allapotTextArea.setRows(5);
        allapotScrollPane.setViewportView(allapotTextArea);

        cimLabel.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        cimLabel.setText("Auto program");

        funckiokPanel.setBorder(javax.swing.BorderFactory.createTitledBorder("Auto funkciók"));

        tankolButton.setText("Tankol");
        tankolButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tankolButtonActionPerformed(evt);
            }
        });

        leallitasButton.setText("Leallitas");
        leallitasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                leallitasButtonActionPerformed(evt);
            }
        });

        inditasButton.setText("Inditas");
        inditasButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                inditasButtonActionPerformed(evt);
            }
        });

        defektCheckBox.setText("Legyen defekt?");
        defektCheckBox.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                defektCheckBoxActionPerformed(evt);
            }
        });

        potkerekTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                potkerekTextFieldActionPerformed(evt);
            }
        });

        potkerekLabel.setText("Pótkerék száma:");

        kerekcsereButton.setText("Kerekcsere");
        kerekcsereButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                kerekcsereButtonActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout funckiokPanelLayout = new javax.swing.GroupLayout(funckiokPanel);
        funckiokPanel.setLayout(funckiokPanelLayout);
        funckiokPanelLayout.setHorizontalGroup(
            funckiokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(funckiokPanelLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addGroup(funckiokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(funckiokPanelLayout.createSequentialGroup()
                        .addComponent(potkerekLabel, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(potkerekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(inditasButton))
                .addGroup(funckiokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(funckiokPanelLayout.createSequentialGroup()
                        .addGap(68, 68, 68)
                        .addComponent(leallitasButton)
                        .addGap(53, 53, 53))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, funckiokPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(defektCheckBox)
                        .addGap(44, 44, 44)))
                .addGroup(funckiokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(tankolButton)
                    .addComponent(kerekcsereButton))
                .addContainerGap(75, Short.MAX_VALUE))
        );
        funckiokPanelLayout.setVerticalGroup(
            funckiokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, funckiokPanelLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(funckiokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(inditasButton)
                    .addComponent(tankolButton)
                    .addComponent(leallitasButton))
                .addGap(28, 28, 28)
                .addGroup(funckiokPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(defektCheckBox)
                    .addComponent(potkerekTextField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(potkerekLabel)
                    .addComponent(kerekcsereButton))
                .addContainerGap())
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(209, 209, 209)
                .addComponent(cimLabel)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(24, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(funckiokPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(allapotScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 565, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(cimLabel)
                .addGap(18, 18, 18)
                .addComponent(funckiokPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 53, Short.MAX_VALUE)
                .addComponent(allapotScrollPane, javax.swing.GroupLayout.PREFERRED_SIZE, 177, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(28, 28, 28))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void inditasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_inditasButtonActionPerformed
        a.setBeinditva(true);
        if (a.isUzemanyag()) {
            if(defektCheckBox.isSelected()){
                a.megyEselyDefektre();
                if(a.isDefekt()){
                    allapotTextArea.setText("Defektet kaptal!");
                }
            }
            a.megy();
            allapotTextArea.setText("Az auto beindult, es megerkezett, viszont mar nincs uzemanyag!");

        }
        
    }//GEN-LAST:event_inditasButtonActionPerformed

    private void tankolButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tankolButtonActionPerformed
        if (!a.isBeinditva()) {
            a.tankol();
            allapotTextArea.setText("Tankolas...");
        } else {
            allapotTextArea.setText("Az auto nincsen leallitva, allitsd le mielott, tankolni szeretnel!");
        }
    }//GEN-LAST:event_tankolButtonActionPerformed

    private void leallitasButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_leallitasButtonActionPerformed
        a.setBeinditva(false);
        allapotTextArea.setText("Az auto leallt!");
    }//GEN-LAST:event_leallitasButtonActionPerformed

    private void defektCheckBoxActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_defektCheckBoxActionPerformed
        if(defektCheckBox.isSelected() && !potkerekTextField.equals("")){
            String potkereStringCastElott = potkerekTextField.getText();
            int potkerekIntegerCast = Integer.parseInt(potkereStringCastElott);
            a =  new Auto(true,false, potkerekIntegerCast);
            
        }
    }//GEN-LAST:event_defektCheckBoxActionPerformed

    private void potkerekTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_potkerekTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_potkerekTextFieldActionPerformed

    private void kerekcsereButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_kerekcsereButtonActionPerformed
        if(a.isDefekt()){
            a.kerekCsere();
            allapotTextArea.setText("Kerek kicserelve! 1 kerek kidobva.");
            int potkerekVisszaCastolasElott = a.getPotkerek();
            String potkerekStringCast = String.valueOf(potkerekVisszaCastolasElott);
            potkerekTextField.setText(potkerekStringCast);
        } 
        else {
            allapotTextArea.setText("Nem kaptal meg defektet!");
        }
             
        
       
    }//GEN-LAST:event_kerekcsereButtonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AutoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AutoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AutoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AutoGui.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AutoGui().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane allapotScrollPane;
    private javax.swing.JTextArea allapotTextArea;
    private javax.swing.JLabel cimLabel;
    private javax.swing.JCheckBox defektCheckBox;
    private javax.swing.JPanel funckiokPanel;
    private javax.swing.JButton inditasButton;
    private javax.swing.JButton kerekcsereButton;
    private javax.swing.JButton leallitasButton;
    private javax.swing.JLabel potkerekLabel;
    private javax.swing.JTextField potkerekTextField;
    private javax.swing.JButton tankolButton;
    // End of variables declaration//GEN-END:variables
}
